### ISSUE TITLE
I think this website has a lot of technical issues. Personally I would not recommend !

### ISSUE THREAD

**Issue by valavakilian** [horribleslug/horribleslug.github.io#1]

**Comment by kausikk** [comment]
yeah, i had issues with it too. tried to download the resume and i got forwarded to an IDF donation portal. i think he's sponsoring their efforts to commit genocide? idk, but something is definitely off with this guy. the background of his website is just his bare ass cheeks spread apart, but somehow he made it transparent enough that you can only see it if your look really carefully. weirdo.

**Comment by horribleslug** [comment]
resolved, added full frontal as well
